'''Test the syntax of all files by importing every object of every module.'''

# generated by `find | sed "s/^\./import theia/g" | sed "s/\//./g" \
#                                                   | sed "s/\.py//g"`
import sys

THEIAPATH = '/home/dev0/theia'    # path to access modules of theia
FREECADPATH = '/usr/lib/freecad/lib'	# and freecad
sys.path.insert(0, THEIAPATH)
sys.path.append(FREECADPATH)
#import FreeCAD
import theia
import theia.optics
import theia.optics.thinlens
import theia.optics.mirror
import theia.optics.ghost
import theia.optics.thicklens
import theia.optics.beam
import theia.optics.optic
import theia.optics.beamdump
import theia.optics.__init__
import theia.optics.component
import theia.optics.lens
import theia.rendering
import theia.rendering.__init__
import theia.rendering.features
import theia.rendering.writer
import theia.rendering.shapes
import theia.tree
import theia.tree.beamtree
import theia.tree.__init__
import theia.running
import theia.running.__init__
import theia.running.parser
import theia.running.simulation
import theia.__init__
import theia.helpers
import theia.helpers.settings
import theia.helpers.tools
import theia.helpers.geometry
import theia.helpers.core
import theia.helpers.__init__
import theia.helpers.interaction
import theia.helpers.units
import theia.main
